name: quran
description: A Quran reading app

version: 2.0.1+6

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  screen_brightness: ^1.0.0
  shared_preferences: ^2.1.0
  wakelock: ^0.6.2
  flutter_native_splash: ^2.2.13
  flutter_local_notifications: ^17.2.3
  workmanager: ^0.5.0
  intl: ^0.19.0
  url_launcher: ^6.0.20
  permission_handler: ^11.3.1
  flutter_vibrate: ^1.1.0
  vibration: ^1.7.4
  geocoding: ^3.0.0
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/elmessiri.ttf
    - assets/fonts/amiri.ttf
    - assets/fonts/arabic_roman.ttf
    - assets/splash/xxxhdpi/
    - assets/notification_page_background.png
    - assets/go_back_button.png
    - assets/qiblah_compass.png
    - assets/background.png
  fonts:
    - family: elmessiri
      fonts:
        - asset: assets/fonts/elmessiri.ttf
    - family: amiri
      fonts:
        - asset: assets/fonts/amiri.ttf
    - family: arabic_roman
      fonts:
        - asset: assets/fonts/arabic_roman.ttf
    - family: thuluth
      fonts:
        - asset: assets/fonts/thuluth.ttf